### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/aiidalab-launch#9]
I got this the first time I run the `start` command (note it had to pull the image, not sure if this is related?

```
$ aiidalab-launch start
Pulling image 'aiidalab/aiidalab-docker-stack:latest'...
Starting container (this may take a while)...
Traceback (most recent call last):
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pizzi/.virtualenvs/generic/bin/aiidalab-launch", line 8, in <module>
    sys.exit(cli())
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/aiidalab_launch/__main__.py", line 251, in start
    instance.start()
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/aiidalab_launch/core.py", line 149, in start
    container = self.client.containers.run(
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/docker/models/containers.py", line 819, in run
    container = self.create(image=image, command=command,
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/docker/models/containers.py", line 878, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/docker/api/container.py", line 428, in create_container
    return self.create_container_from_config(config, name)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/docker/api/container.py", line 438, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/docker/api/client.py", line 296, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pizzi/.virtualenvs/generic/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=1)
```

Running this immediately after worked (it took ~30 seconds I think?):
```
$ aiidalab-launch start --no-browser
Starting previously created container (this may take a while)...
Open the following URL to access AiiDAlab:

  http://localhost:8888/?token=6beb858de83c137fb3e7157b8308cbdf55ae0da81d1e513cb3b343dd270d2b6c

Home mounted: /home/pizzi/aiidalab -> /home/aiida
```

**Comment by csadorf** [comment]
I was able to reproduce the issue by first purging local images. I suspect the bug might have been introduced with #8 and is related to https://github.com/docker/docker-py/issues/1070.

**Comment by csadorf** [comment]
I now suspect the issue is actually an unexpected side-effect of https://github.com/aiidalab/aiidalab-launch/pull/7, where we first attempt to obtain the docker client with a very short timeout (1 sec): https://github.com/aiidalab/aiidalab-launch/blob/01b21405789b221bd0680a50d5ebaf0c7a2e08d2/aiidalab_launch/util.py#L22-L23
